"""add_pdf_blob_name_to_resumes

Revision ID: fd84be2d0120
Revises: 05e5fd18b944
Create Date: 2026-02-10 16:45:02.752258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd84be2d0120'
down_revision = '05e5fd18b944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_blob_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'pdf_blob_name')
    # ### end Alembic commands ###
